$scriptPath = $PSScriptRoot

# Set the path to your spec file (modify as needed)
$specFilePath = Resolve-Path -Path (Join-Path -Path $scriptPath -ChildPath "../build.spec")
$pyprojectPath = Resolve-Path -Path (Join-Path -Path $scriptPath -ChildPath "../pyproject.toml")

$projectVersion = $null
$inProjectSection = $false
foreach ($line in Get-Content -Path $pyprojectPath) {
	$trimmed = $line.Trim()
	if ($trimmed.StartsWith("[")) {
		$inProjectSection = ($trimmed -eq "[project]")
		continue
	}
	if ($inProjectSection -and $trimmed -match '^version\s*=\s*"([^"]+)"') {
		$projectVersion = $Matches[1]
		break
	}
}

if (-not $projectVersion) {
	throw "Could not parse [project].version from $pyprojectPath"
}

$expectedExeName = "NexusDownloadFlow-v$projectVersion.exe"

Write-Host "Spec path: $specFilePath"
Write-Host "Project version: $projectVersion"

# Define/create the output directory, then resolve it
$outputDirRaw = Join-Path -Path $scriptPath -ChildPath "../dist"
if (-not (Test-Path -Path $outputDirRaw)) {
	New-Item -ItemType Directory -Path $outputDirRaw | Out-Null
}
$outputDir = Resolve-Path -Path $outputDirRaw

Write-Host "Output path: $outputDir"

# Sync dependencies and run PyInstaller from the uv-managed environment
uv sync --locked --extra dev --python 3.14
uv run --python 3.14 pyinstaller "$specFilePath"

# Optional: Clean up any temporary files generated by PyInstaller
#Remove-Item -Path "$outputDir\__pycache__" -Recurse -Force

$expectedExePath = Join-Path -Path $outputDir -ChildPath $expectedExeName
if (Test-Path -Path $expectedExePath) {
	Write-Host "Executable built successfully: $expectedExePath"
} else {
	Write-Host "Build finished, but expected executable was not found: $expectedExePath"
}
