$programName = "NexusDownloadFlow-2023"

$scriptPath = $PSScriptRoot

# Set the path to your spec file (modify as needed)
$specFilePath = Resolve-Path -Path (Join-Path -Path $scriptPath -ChildPath "../$programName.spec")

Write-Host "Spec path: $specFilePath"

# Define the name of the output directory (modify as needed)
$outputDir = Resolve-Path -Path (Join-Path -Path $scriptPath -ChildPath "../dist")

Write-Host "Output path: $outputDir"

# Run PyInstaller to build the executable using the spec file
pyinstaller "$specFilePath"

# Optional: Clean up any temporary files generated by PyInstaller
#Remove-Item -Path "$outputDir\__pycache__" -Recurse -Force

Write-Host "Executable built successfully!"