$scriptPath = $PSScriptRoot

# Set the path to your spec file (modify as needed)
$specFilePath = Resolve-Path -Path (Join-Path -Path $scriptPath -ChildPath "../build.spec")

Write-Host "Spec path: $specFilePath"

# Define/create the output directory, then resolve it
$outputDirRaw = Join-Path -Path $scriptPath -ChildPath "../dist"
if (-not (Test-Path -Path $outputDirRaw)) {
	New-Item -ItemType Directory -Path $outputDirRaw | Out-Null
}
$outputDir = Resolve-Path -Path $outputDirRaw

Write-Host "Output path: $outputDir"

# Sync dependencies and run PyInstaller from the uv-managed environment
uv sync --locked --extra dev --python 3.14
uv run --python 3.14 pyinstaller "$specFilePath"

# Optional: Clean up any temporary files generated by PyInstaller
#Remove-Item -Path "$outputDir\__pycache__" -Recurse -Force

Write-Host "Executable built successfully!"
